ReferenceError({
  name: "ReferenceError",
  message: "something went wrong",
  stack: "ReferenceError: something went wrong\n    at Object.<anonymous> (/home/hyurl/git/fron/test/data/index.js:16:26)\n    at Module._compile (module.js:541:32)\n    at Object.Module._extensions..js (module.js:550:10)\n    at Module.load (module.js:456:32)\n    at tryModuleLoad (module.js:415:12)\n    at Function.Module._load (module.js:407:3)\n    at Module.require (module.js:466:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/home/hyurl/git/fron/test/get-types.js:12:5)\n    at Module._compile (module.js:541:32)\n    at Object.Module._extensions..js (module.js:550:10)\n    at Module.load (module.js:456:32)\n    at tryModuleLoad (module.js:415:12)\n    at Function.Module._load (module.js:407:3)\n    at Module.require (module.js:466:17)\n    at require (internal/module.js:20:19)\n    at /home/hyurl/git/fron/node_modules/mocha/lib/mocha.js:250:27\n    at Array.forEach (native)\n    at Mocha.loadFiles (/home/hyurl/git/fron/node_modules/mocha/lib/mocha.js:247:14)\n    at Mocha.run (/home/hyurl/git/fron/node_modules/mocha/lib/mocha.js:576:10)\n    at Object.<anonymous> (/home/hyurl/git/fron/node_modules/mocha/bin/_mocha:637:18)\n    at Module._compile (module.js:541:32)\n    at Object.Module._extensions..js (module.js:550:10)\n    at Module.load (module.js:456:32)\n    at tryModuleLoad (module.js:415:12)\n    at Function.Module._load (module.js:407:3)\n    at Function.Module.runMain (module.js:575:10)\n    at startup (node.js:159:18)\n    at node.js:444:3"
})